image: docker:19.03.0

stages:
  - build
  - build-push-image
  - deploy-image


variables:
  CONTAINER_IMAGE_MASTER: $DOCKER_REGISTRY_URI/roomfix-front:${CI_COMMIT_SHORT_SHA}

before_script:
  - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_URI

build-master:
  stage: build
  image: node
  script:
    - yarn install --ignore-optional --frozen-lockfile
    - REACT_APP_API_URI=/api yarn build:prod
  artifacts:
    paths:
      - build
  only:
    - master

build-push-image-master:
  services:
    - docker:19.03.0-dind
  stage: build-push-image
  script:
    - docker build -t ${CONTAINER_IMAGE_MASTER} .
    - docker push ${CONTAINER_IMAGE_MASTER}
  only:
    - master
  cache: {}

# deploy-image-master:
#   image:
#     name: bitnami/kubectl:1.14
#     entrypoint: [""]
#   stage: deploy-image
#   script:
#     - echo -n $KUBERNETIX_CONFIG | base64 -d > ./kubeconfig
#     - kubectl set image deployment searchix-front searchix-front=${CONTAINER_IMAGE_MASTER} --kubeconfig ./kubeconfig --namespace default
#   only:
#     - master
#   cache: {}
